### ISSUE TITLE
Selected date is wrong (One day before)

### ISSUE THREAD

**Issue by sarpdoruk** [jaykz52/CKCalendar#11]
In demo application, when I select a date, it is shown in a UILabel I guess at the bottom of the page but it is wrong.  For example when I select August 16th 2012, the output is always the one day before; August 15th 2012.

**Comment by crazyramirez** [comment]
Dates are stored properly, simply make an NSDateFormatter to represent the selected date.

In CKViewController.m change this lines of code:
- (void)calendar:(CKCalendarView *)calendar didSelectDate:(NSDate *)date {
  NSDateFormatter *formatter = [[NSDateFormatter alloc] init];
  [formatter setDateFormat: @"yyyy-MM-dd"];
  NSString *stringFromDate = [formatter stringFromDate:date];
  self.dateLabel.text = stringFromDate;
  }

**Comment by jaykz52** [comment]
@crazyramirez That would certainly fix the issue. If you want to make this change and submit a pull request, I'll get that merged in. Thanks!

**Comment by crazyramirez** [comment]
Another method is to write a function to get the desired date and set a NSString
For example:

Write this function in the top of your code:
- (NSString *) stringFromDate: (NSDate *) date
  {
       NSDateFormatter \* formatter = [[NSDateFormatter alloc] init];
       [formatter setDateFormat: @ "dd MMMM yyyy"];
       NSString \* stringFromDate = [formatter stringFromDate: date];
       stringFromDate return;
  }

From CKCalendarDelegate:
- (Void) calendar (CKCalendarView *) didSelectDate calendar: (NSDate *) date
  {
       self.dateLabel.text = [self stringFromDate: date];
  }

**Comment by jaykz52** [comment]
I think for the context (an example of how to interact with CKCalendarView), I think the first solution is sufficient. Either way is fine.

**Comment by sarpdoruk** [comment]
Thanks for the tips, will try out those solutions.

**Comment by jaykz52** [comment]
I've added date formatting to the label to reduce confusion.
