### ISSUE TITLE
Several selected days

### ISSUE THREAD

**Issue by cassio-rossi** [jaykz52/CKCalendar#16]
I would like to suggest the creation of a function that allows to show several selected days in the calendar like, for example: sundays and saturdays, or holidays.
Is that possible?
Thanks and congrats for the code.
Cassio

**Comment by jaykz52** [comment]
In light of this feature request and others, I'm going to work on a more easily extensible implementation that will allow people to more easily extend the calendar to meet their needs (along the lines of UITableView behavior)

**Comment by jaykz52** [comment]
Check out what I'm working on in https://github.com/jaykz52/CKCalendar/tree/v1. It should be possible to support the feature you mention above using the newer API.

Now, you can arbitrarily style dates as they are drawn in the calendar, so by handling the `didSelectDate` protocol method and reloading the dates within the "selected" range to change their background color to a color of your choosing, this should allow you to have the notion of a range of selected dates.

**Comment by jaykz52** [comment]
v1.0.0 allows you to effectively 'select' multiple dates via the delegate keeping track of selected dates and styling accordingly via `configureDateItem:forDate:` method
