### ISSUE TITLE
Default styling causes poor frame rate.

### ISSUE THREAD

**Issue by Kenrik** [jaykz52/CKCalendar#17]
Animating into a view with the Calendar on it or animating the Calendar (Tested on iPhone 4) results in terrible frame rates/choppyness however after removing the code below (with little visual loss) it becomes butter smooth. I suggest that you either use a .png for the opacity/shadow or ditch it all together because otherwise you get just awful performance.     

```
self.layer.cornerRadius = 6.0f;
self.layer.shadowOffset = CGSizeMake(2, 2);
self.layer.shadowRadius = 2.0f;
self.layer.shadowOpacity = 0.4f;
self.layer.borderColor = [UIColor blackColor].CGColor;
self.layer.borderWidth = 1.0f;
```

**Comment by jaykz52** [comment]
@Kenrik You can of course disable the shadow without subclassing or making the changes you suggest above. After you init the calendar in your code, you can turn off the shadowing in the code that's utilizing the calendar. You might also be able to turn enable rasterization on the calendar, but not sure what the results will be.

I'll look at this more later today. The shadowing is subtle, so I might just remove the shadowing defaults for now.
