### ISSUE TITLE
Only make dates pulled from a XML feed selectable

### ISSUE THREAD

**Issue by hassanmah** [jaykz52/CKCalendar#26]
I'm using CKCalendarView for an events app. I'm parsing dates of event via a XML (RSS feed) into an array, anyone have any idea how I can put those dates into the calendar, so only them dates are selectable?

Thanks in advance

**Comment by jaykz52** [comment]
I'm considering adding a delegate method for determining whether a particular date is selectable. Essentially the calendar would ask the delegate if a date was selectable right before showing it. You could then put all of your logic that depends on the XML into your own class which the calendar would talk to.

**Comment by jaykz52** [comment]
Closing as this is not a feature this calendar UI control will ever be responsible for (see above comment)
