### ISSUE TITLE
Create a new tag for cocoapods.

### ISSUE THREAD

**Issue by amitvaghela** [jaykz52/CKCalendar#27]
Hi,

Please create a new tag so that cocoapod user get updated code.

Thanks,
Amit

**Comment by AL333Z** [comment]
:+1:

**Comment by jaykz52** [comment]
I suck at life. Will get this done this week. To my credit, I've been in the process of moving across country

**Comment by jaykz52** [comment]
I seem to have had push access removed from CocoaPods Specs main repo, but I've got a PR outstanding for v0.2.0 and v1.0.0 (just released, changes previous APIs).

**Comment by jaykz52** [comment]
My PR has been merged in CocoaPods/Specs master repo. Enjoy!
