### ISSUE TITLE
Any way to get start date and end date

### ISSUE THREAD

**Issue by shinrenpan** [jaykz52/CKCalendar#34]
I need to get start date and end date in current calendar
Any simple way to do it ?

**Comment by jaykz52** [comment]
Can you elaborate? The calendar will render dates from from whatever the system min date is to whatever the system max date is

**Comment by shinrenpan** [comment]
Ok, for example

```
I set calendar.onlyShowCurrentMonth = NO
```

Current month is  `April 2013`

In the calendar the start date is `March 31 2013`, the end date is `May 11 2013`

Any way to get March 31 2013 and  May 11 2013 (parameters or methods or delegates)

![calendar](https://f.cloud.github.com/assets/1157368/412665/bebac2ba-abc4-11e2-8fd8-840875c34046.png)

**Comment by jaykz52** [comment]
+1 for the pretty picture. Currently, there's no way to get this. A few solutions we could do:
1. expose the calendar's currently shown dates as an array (probably my preference).
2. expose the start/end dates (the dev could infer everything between)
3. something else
