### ISSUE TITLE
Layout update for popover use

### ISSUE THREAD

**Issue by vincentnl** [jaykz52/CKCalendar#35]
I used it in a popover. Very good work m8! really liked it.

I added another delegate method, so the popoverview size will keep track with the calendar size.
the method didchangemonth could not be used for this, as the calendar layout was only updated afterward.

put the hook in layoutsubviews.

-(void)calendar:(CKCalendarView *)calendar didLayoutCalendar:(CGRect)rect{
        self.contentSizeForViewInPopover=calendar.frame.size;
}

**Comment by jaykz52** [comment]
Sorry for the delay. You're right about this issue. I'll see about getting this merged this week.
