### ISSUE TITLE
Disable last days and futurs

### ISSUE THREAD

**Issue by DivideK** [jaykz52/CKCalendar#39]
Hello,

First, thank you for this amazing calendar.

I need to disable the last dates and those in after 2 months for example.
How can I make this?

Thank you

**Comment by DivideK** [comment]
Hello,

It's okay, I've found a way to do it.

Thank you again for this calendar.

**Comment by jaykz52** [comment]
Awesome. Glad to hear. Generally speaking, you should be able to use the CKCalendarViewDelegate methods to do what you're talking about (returning NO from willSelectDate: for those dates you wish to disable). You can also style disabled dates differently to your liking.

**Comment by DivideK** [comment]
Yes, it's exactly what I've done. I have change disabledDate by enabledDate and inverted the willSelectDate return.

Thanks for the reply  ;)
