### ISSUE TITLE
add day with an Array

### ISSUE THREAD

**Issue by ygoez** [jaykz52/CKCalendar#43]
How I can display dates with an Array???

**Comment by jaykz52** [comment]
Can you elaborate?

**Comment by ygoez** [comment]
Hi,

I have 3 Arrays:
NSArray *array1 =  [NSArray arrayWithObjects:@"2013-07-22",@"2013-07-23",@"2013-07-24",nil];
NSArray *array2 =  [NSArray arrayWithObjects:@"2013-08-22",@"2013-09-23",@"2013-08-10",nil];
NSArray *array3 =  [NSArray arrayWithObjects:@"2013-09-22",@"2013-09-23",@"2013-09-09",",nil];

I want that the data in the arrays are marked with different colors in the Calendar-View. I don't know how I display the data from the array in the Calendar. I tried this, but it only shows the last element in the array.

for(int i=0; i<array1.count;i++){
        self.disabledDates = @[[self.dateFormatter dateFromString:[array objectAtIndex:i]]];
        }

**Comment by fastred** [comment]
If I understand it correctly, you can use delegate method `calendar:configureDateItem:forDate:` to configure text and background colors of cells.
