### ISSUE TITLE
Get Selected Date cell and modify it.

### ISSUE THREAD

**Issue by avramirez** [jaykz52/CKCalendar#47]
I'm trying to modify the cell/box of the selected item and change its properties, like changing its font-size or border. The delegate method I'm using is

```
- (void)calendar:(CKCalendarView *)calendar didSelectDate:(NSDate *)date {
}

```

but there is no object to use to access the cell.

I'm just new to iOS , sorry for my newbie question.

**Comment by anujism** [comment]
I also have the same problem. Please let me know how to access dateItem in didSelectDate.

**Comment by avramirez** [comment]
Here is a solution by @anujism 

https://github.com/anujism/CKCalendar

I also tried to do a pull request to this project. It seems like this is not maintained anymore. I'll try yours :+1: 

https://github.com/jaykz52/CKCalendar/pull/53
