### ISSUE TITLE
Initializing calendar with a selected date on another month

### ISSUE THREAD

**Issue by markrickert** [jaykz52/CKCalendar#8]
It seems that the calendar always displays the current month on init even when a date in a previous month is specified with the `selectedDate` property.

For instance:

``` obj-c
_calendarView = [[CKCalendarView alloc] initWithStartDay:startSunday];
_calendarView.delegate = self;
_calendarView.selectedDate = _theDate; //_theDate is last month
[self.view addSubview:_calendarView];
```

When `_theDate` is in the previous month, the calendar will display today's month and when navigation to last month, it will properly have the selected date colored.

**Comment by jaykz52** [comment]
@markrickert this works how you expect with the latest in master. I'm not entirely convinced a dev would want this 100%, but it's likely the majority, so I'm game. It's a one line change for those who need it to behave differently.
